# Generated by Django 2.2a1 on 2019-01-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='isFavorite',
            field=models.BooleanField(default=False),
        ),
    ]
